name: Auto Release from package.json

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 确保能获取 tags
          token: ${{ secrets.PAT_TOKEN }} # 使用PAT token进行checkout

      - name: Get current version from package.json
        id: package-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check-tag
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.package-version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config --global user.email "bot@clisthub.com"
          git config --global user.name "Bot"
          git tag "v${{ steps.package-version.outputs.version }}"
          git push origin "v${{ steps.package-version.outputs.version }}"

      - name: Create GitHub Release
        if: steps.check-tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          name: Release v${{ steps.package-version.outputs.version }}
          body: |
            Automated release for version v${{ steps.package-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
